apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        kind: build
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          
      - id: build-go-binary
        name: Build Go binary
        kind: build
        uses: docker://golang:latest
        run: |
          GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o myapp --buildvcs=0
        env:
          CGO_ENABLED: "0"

  deploy:
    steps:      
      - name: Deploy to Kubernetes
        kind: deploy
        uses: cloudbees-io/helm-deploy@v1
        
